package dev.kopandazavr.codexmonitor;

import java.util.List;
import java.util.Locale;
import java.util.UUID;

/** Pure normalization and short-name rules shared by the durable project-profile registry. */
final class ProjectProfileRules {
    private ProjectProfileRules() {}

    static String collapseWhitespace(String value) {
        if (value == null) return "";
        return value.trim().replaceAll("\\s+", " ");
    }

    static String normalizeAlias(String value) {
        return collapseWhitespace(value).toLowerCase(Locale.ROOT);
    }

    static String automaticAcronym(String fullName) {
        String clean = collapseWhitespace(fullName);
        if (clean.isEmpty()) return "";
        StringBuilder acronym = new StringBuilder();
        for (String word : clean.split(" ")) {
            if (word.isEmpty()) continue;
            acronym.appendCodePoint(Character.toUpperCase(word.codePointAt(0)));
        }
        return acronym.toString();
    }

    static String fallbackShort(String watchdogShort, String primaryAlias) {
        // Local project identity owns the automatic short. Calendar metadata remains read-only
        // input and must not pin the fallback after the user changes the Primary alias.
        return automaticAcronym(primaryAlias);
    }

    static String effectiveShort(String localOverride, String watchdogShort, String primaryAlias) {
        String local = collapseWhitespace(localOverride);
        return local.isEmpty() ? fallbackShort(watchdogShort, primaryAlias) : local;
    }

    static String badgeText(String localOverride, String watchdogShort, String primaryAlias) {
        String full = collapseWhitespace(primaryAlias);
        String shortName = effectiveShort(localOverride, watchdogShort, full);
        return shortName.isEmpty() ? full : "[" + shortName + "] " + full;
    }

    /**
     * Legacy corruption could leave a generated default profile owning one invisible alias.
     * Only that exact autogenerated/default signature is reclaimable.
     */
    static boolean isReclaimableLegacyOrphan(String profileId, List<String> aliases,
            String primaryAlias, String shortOverride, String iconKey, String colorKey,
            String requestedAlias) {
        String normalized = normalizeAlias(requestedAlias);
        if (normalized.isEmpty() || !isGeneratedProfileId(profileId)
                || aliases == null || aliases.size() != 1
                || !collapseWhitespace(shortOverride).isEmpty()
                || !"folder".equals(iconKey) || !"gray".equals(colorKey)
                || !normalizeAlias(primaryAlias).equals(normalized)) {
            return false;
        }
        return normalizeAlias(aliases.get(0)).equals(normalized);
    }

    private static boolean isGeneratedProfileId(String profileId) {
        String prefix = "project:";
        if (profileId == null || !profileId.startsWith(prefix)) return false;
        try {
            UUID.fromString(profileId.substring(prefix.length()));
            return true;
        } catch (IllegalArgumentException exception) {
            return false;
        }
    }
}
