#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/app/src/main/java/dev/kopandazavr/codexmonitor"
RES="$ROOT/app/src/main/res"
grep -Fq 'versionCode = 47' "$ROOT/app/build.gradle.kts"
grep -Fq 'versionName = "2.21.0"' "$ROOT/app/build.gradle.kts"
grep -Fq 'VERSION_CODE = 47' "$SRC/AppConstants.java"
grep -Fq 'VERSION_NAME = "2.21.0"' "$SRC/AppConstants.java"
NOW="$RES/xml/preferences_settings_now_bar.xml"
grep -Fq 'android:title="Notifications"' "$NOW"
grep -Fq 'android:summary="System notification settings"' "$NOW"
! grep -Fq 'Idle reminder cadence' "$NOW"
! grep -Fq 'idle_reminder_cadence_ui' "$NOW"
! grep -Fq 'now_bar_setup_help' "$NOW"
! grep -Fq 'now_bar_preview' "$NOW"
! grep -Fq 'Live notification settings' "$NOW"
grep -Fq 'Settings.ACTION_APP_NOTIFICATION_SETTINGS' "$SRC/SettingsActivity.java"
! grep -Fq 'Settings.ACTION_APP_NOTIFICATION_PROMOTION_SETTINGS' "$SRC/SettingsActivity.java"
! grep -Fq 'Samsung Now Bar setup' "$SRC/SettingsActivity.java"
! grep -Fq 'Sample Live Update started' "$SRC/SettingsActivity.java"
grep -Fq 'ProcessNotificationManager.clearAll(requireContext())' "$SRC/SettingsActivity.java"
grep -Fq 'ProcessNotificationMode.set(requireContext(), next)' "$SRC/SettingsActivity.java"
grep -Fq 'DualUsageNotificationManager.repostFromCache' "$SRC/SettingsActivity.java"
grep -Fq 'DEFAULT_CADENCE_MINUTES = 5' "$SRC/IdleProcessState.java"
grep -Fq 'return DEFAULT_CADENCE_MINUTES;' "$SRC/IdleProcessState.java"
grep -Fq 'return DEFAULT_CADENCE_MINUTES * 60_000L;' "$SRC/IdleProcessState.java"
! grep -Fq 'KEY_CADENCE_UI' "$SRC/IdleProcessState.java"
! grep -Fq '"10".equals' "$SRC/IdleProcessState.java"
grep -Fq 'COMBINED = "combined"' "$SRC/ProcessNotificationMode.java"
grep -Fq 'PER_PROCESS = "per_process"' "$SRC/ProcessNotificationMode.java"
grep -Fq 'GROUPED = "grouped"' "$SRC/ProcessNotificationMode.java"
grep -Fq 'WatchdogObservationDiagnostics.logRejected' "$SRC/CalendarProcessReader.java"
grep -Fq 'WatchdogObservationDiagnostics.logRejected' "$SRC/GoogleCalendarProcessSource.java"
grep -Fq '"marker_present"' "$SRC/WatchdogObservationDiagnostics.java"
grep -Fq '"marker_valid"' "$SRC/WatchdogObservationDiagnostics.java"
grep -Fq '"project_present"' "$SRC/WatchdogObservationDiagnostics.java"
grep -Fq '"role_present"' "$SRC/WatchdogObservationDiagnostics.java"
grep -Fq '"project_short_present"' "$SRC/WatchdogObservationDiagnostics.java"
grep -Fq '"topic_present"' "$SRC/WatchdogObservationDiagnostics.java"
grep -Fq '"normalized_identity"' "$SRC/WatchdogObservationDiagnostics.java"
grep -Fq '"watchdog_identity_changed"' "$SRC/WatchdogObservationDiagnostics.java"
grep -Fq 'POLL_INTERVAL_MS = TimeUnit.SECONDS.toMillis(10)' "$SRC/ProcessNotificationScheduler.java"
! grep -Fq '"calendar_poll_requested"' "$SRC/ProcessNotificationScheduler.java"
! grep -Fq '"calendar_poll_completed"' "$SRC/ProcessNotificationScheduler.java"
! grep -Fq '"calendar_poll_recovery_scheduled"' "$SRC/ProcessNotificationScheduler.java"
grep -Fq '"calendar_poll_recovered"' "$SRC/MonitorHealthDiagnostics.java"
grep -Fq '"calendar_poll_failure_changed"' "$SRC/MonitorHealthDiagnostics.java"
grep -Fq '"observation_source_changed"' "$SRC/MonitorHealthDiagnostics.java"
grep -Fq '"monitor_counts_changed"' "$SRC/MonitorHealthDiagnostics.java"
grep -Fq 'android:key="diagnostic_monitor_health"' "$RES/xml/preferences_settings_diagnostics.xml"
grep -Fq 'MonitorHealthDiagnostics.summary(requireContext())' "$SRC/SettingsActivity.java"
grep -Fq 'REQUIRED_TOTAL = 5' "$SRC/SetupReadiness.java"
grep -Fq 'RECOMMENDED_TOTAL = 1' "$SRC/SetupReadiness.java"
! grep -Fq 'POST_PROMOTED_NOTIFICATIONS' "$SRC/SetupReadiness.java"
! grep -Fq 'POST_PROMOTED_NOTIFICATIONS' "$SRC/OnboardingActivity.java"
grep -Fq 'M54,7 A47,47' "$RES/drawable/ic_notification_codex_monitor.xml"
grep -Fq 'new DiagonalStripeDrawable(' "$SRC/IdleReminderOverlayService.java"
echo "Codex Monitor 2.21 source contract PASS"
