#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/app/src/main/java/dev/kopandazavr/codexmonitor"
RES="$ROOT/app/src/main/res"

VERSION_CODE="$(awk '/versionCode = / { print $3; exit }' "$ROOT/app/build.gradle.kts")"
[[ "$VERSION_CODE" -ge 50 ]]
grep -Fq 'VERSION_CODE = ' "$SRC/AppConstants.java"
grep -Fq 'VERSION_NAME = ' "$SRC/AppConstants.java"

grep -Fq 'ProjectProfileStore.resolve(this, process.project)' "$SRC/MainActivity.java"
grep -Fq 'ProjectProfileStore.resolve(this, idle.project)' "$SRC/MainActivity.java"
grep -Fq 'ProjectSettingsDialog.show' "$SRC/MainActivity.java"
grep -Fq 'TextView role = Ui.text(this, process.role' "$SRC/MainActivity.java"
grep -Fq 'TextView role = Ui.text(this, idle.role' "$SRC/MainActivity.java"

grep -Fq '"seed:data-matrix", "Data Matrix"' "$SRC/ProjectProfileStore.java"
grep -Fq '"DM", "terminal", COLOR_GREEN' "$SRC/ProjectProfileStore.java"
grep -Fq '"seed:codex-monitor", "Codex Monitor"' "$SRC/ProjectProfileStore.java"
grep -Fq '"seed:orders-cigarettes", "Заказы сигарет"' "$SRC/ProjectProfileStore.java"
grep -Fq '"seed:mira-technical", "Mira Technical"' "$SRC/ProjectProfileStore.java"
grep -Fq '"Написание книг про ии будущего"' "$SRC/ProjectProfileStore.java"
grep -Fq '"seed:mira-universe", "Mira Universe"' "$SRC/ProjectProfileStore.java"
grep -Fq 'UUID.randomUUID()' "$SRC/ProjectProfileStore.java"
grep -Fq 'normalizeAlias' "$ROOT/shared/src/main/java/dev/kopandazavr/codexmonitor/ProjectProfileRules.java"
grep -Fq 'effectiveShort' "$ROOT/shared/src/main/java/dev/kopandazavr/codexmonitor/ProjectProfileRules.java"
grep -Fq 'Make another alias Primary before deleting this one.' "$SRC/ProjectProfileStore.java"
grep -Fq 'That alias already belongs to ' "$SRC/ProjectProfileStore.java"

grep -Fq 'COLOR_GRAY = "gray"' "$SRC/ProjectProfileStore.java"
grep -Fq '0xFFE65248' "$SRC/ProjectProfileStore.java"
grep -Fq '0xFFDF8247' "$SRC/ProjectProfileStore.java"
grep -Fq '0xFFEDC75C' "$SRC/ProjectProfileStore.java"
grep -Fq '0xFF6EB363' "$SRC/ProjectProfileStore.java"
grep -Fq '0xFF4D81EF' "$SRC/ProjectProfileStore.java"
grep -Fq '0xFF8155E6' "$SRC/ProjectProfileStore.java"
grep -Fq '0xFFE07EAD' "$SRC/ProjectProfileStore.java"
grep -Fq '"heart", "heart_filled"' "$SRC/ProjectProfileStore.java"
test -f "$RES/drawable/ic_project_heart.xml"
test -f "$RES/drawable/ic_project_heart_filled.xml"
test -f "$ROOT/app/src/main/assets/licenses/OpenAI-Apps-SDK-UI-LICENSE.txt"

grep -Fq 'warning = acceleratedWarning && percent > 0;' "$SRC/UsageWaveView.java"
grep -Fq 'RESET_LIME = 0xFFB7F34A' "$SRC/ResetProgress.java"
grep -Fq 'ResetProgress.elapsedPercent' "$SRC/MainActivity.java"
grep -Fq 'ResetProgress.elapsedPercent' "$SRC/DualUsageNotificationManager.java"
grep -Fq 'ResetProgress.RESET_LIME' "$SRC/NowBarManager.java"
! grep -R -Fq 'ResetProgress.timeRemainingPercent' "$SRC"
grep -Fq '#B7F34A' "$RES/layout/notification_usage_dual_bars.xml"
grep -Fq '#B7F34A' "$RES/layout/notification_usage_dual_bars_expanded.xml"

grep -Fq 'resetLabel(System.currentTimeMillis())' "$SRC/UsageBurnChartView.java"
! grep -Fq 'samples.size() + " samples"' "$SRC/UsageBurnChartView.java"

echo "Codex Monitor 2.24 source contract PASS"
